<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CryptoWidget.Models</RootNamespace>
    <AssemblyName>CryptoWidget.Models</AssemblyName>
  </PropertyGroup>

</Project>
