<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CryptoWidget.Common</RootNamespace>
    <AssemblyName>CryptoWidget.Common</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoWidget.Models\CryptoWidget.Models.csproj" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>

</Project>
